Repository FRONTENDSCHOOL10/seven-11, pull requests merged in 2024-09, with the labels that each got.

#56 [Feat] 채팅 리스트 구현
  public/chatIcon.svg
  src/components/Chat/Chat.jsx
  src/components/Chat/Chat.module.css
  src/components/Chat/LocationTime.jsx
  src/hooks/useFetch.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/Chatroom.jsx
  src/pages/Chat/Chatrooms.jsx
  src/router.jsx
  src/stores/.store
  src/stores/useChatStore.js
  src/utils/getTimeDifference.js
Labels: 🏗️Markup, 💄Styling, 🔨Feature

#57 [Feat] 메인(푸터) 내비게이션 구현
  public/sprite.svg
  public/stack.svg
  src/App.jsx
  src/components/FooterNav.jsx
  src/layouts/RootLayout.jsx
  src/pages/Search.jsx
  src/router.jsx
Labels: 🏗️Markup, 🔨Feature

#65 [Feat] 검색 바 컴포넌트 구현
  src/components/LeftIcon.jsx
  src/components/SearchBar.jsx
  src/components/SearchIcon.jsx
  src/layouts/RootLayout.jsx
  src/pages/Search.jsx
  tailwind.config.js
Labels: 🏗️Markup, 💄Styling, 🔨Feature

#67 [Feat] 셀렉트 버튼 컴포넌트
  public/stack.svg
  src/components/DownIcon.jsx
  src/components/LeftIcon.jsx
  src/components/SearchIcon.jsx
  src/components/SelectButton.jsx
  src/pages/HomePage.jsx
Labels: 🏗️Markup, 💄Styling, 🔨Feature, 👩‍🔧Refactor

#69 [Feat] 댓글/메세지 전송 바 컴포넌트
  public/stack.svg
  src/components/PlusIcon.jsx
  src/components/SendIcon.jsx
  src/components/SendMessageBar.jsx
  src/pages/HomePage.jsx
  src/styles/components/component.css
Labels: 🏗️Markup, 💄Styling, 🔨Feature, 👩‍🔧Refactor

#73 [Feat] 기본(가로) 버튼
  src/components/LeftIcon.jsx
  src/components/NormalButton.jsx
  src/pages/HomePage.jsx
  src/pages/SignUp.jsx
  src/pages/StudyPost.jsx
  tailwind.config.js
Labels: 🏗️Markup, 💄Styling, 🔨Feature, 👩‍🔧Refactor

#74 [Feat] 배지 컴포넌트
  src/components/Badge.jsx
  src/pages/QuestionPage/QuestionPage.jsx
Labels: 🏗️Markup, 💄Styling, 🔨Feature

#79 [Design] 회원가입 css 변경
  src/components/CheckButton.jsx
  src/components/GenderRadio.jsx
  src/components/InputText.jsx
  src/components/SubTitle.jsx
  src/pages/SignUp.jsx
Labels: 💄Styling

#80 [Feat] 더보기 모달 컴포넌트
  src/components/CloseIcon.jsx
  src/components/DownIcon.jsx
  src/components/MoreModal.jsx
  src/components/TopNav.jsx
  src/pages/HomePage.jsx
  src/pages/Search.jsx
  src/pages/StudyDetail.jsx
  src/stores/useUserStore.js
  src/styles/components/component.css
Labels: 🏗️Markup, 💄Styling, 🔨Feature, ✂️modify

#91 [Feat] 카테고리 드롭다운
  src/components/CategoryDropdown.jsx
  src/components/PostButton.jsx
  src/components/PostIcon.jsx
  src/pages/HomePage.jsx
  src/pages/Profile/EditProfile.jsx
Labels: 🔨Feature, 👩‍🔧Refactor

#100 [Feat] 작성자 정보 컴포넌트
  src/components/AuthorProfile.jsx
Labels: 🏗️Markup, 💄Styling, 🔨Feature

#97 [Design] 회원가입 페이지 스타일링
  src/components/CheckButton.jsx
  src/components/DateButton.jsx
  src/components/GenderRadio.jsx
  src/components/InputText.jsx
  src/components/SubTitle.jsx
  src/pages/SignUp.jsx
Labels: 🏗️Markup, 💄Styling

#99 [Design] 카테고리 선택 페이지 스타일링
  src/components/CheckButton.jsx
  src/pages/SelectCategory.jsx
Labels: 🏗️Markup, 💄Styling

#101 [Modify] 회원가입 페이지 코드 수정
  src/components/SmallText.jsx
  src/components/SubTitle.jsx
  src/pages/SignUp.jsx
Labels: ⚠️Bug

#130 회원가입 기능 구현
  index.html
  src/components/AddressSearch.jsx
  src/components/DateButton.jsx
  src/components/GenderRadio.jsx
  src/components/InputText.jsx
  src/pages/Login.jsx
  src/pages/SelectCategory.jsx
  src/pages/SignUp.jsx
Labels: 🔨Feature

#139 [Feat] 질문 게시글 페이지, 디테일 페이지
  src/App.jsx
  src/api/pb.js
  src/components/Board/PostImgButton.jsx
  src/components/Board/PostSection.jsx
  src/components/Board/PostUser.jsx
  src/components/Board/QuestionForm.jsx
  src/components/Board/Reply.jsx
  src/components/Board/SelectCategory.jsx
  src/components/Chat/ChatModal.jsx
  src/components/FooterNav.jsx
  src/layouts/RootLayout.jsx
  src/pages/LandingPage.jsx
  src/pages/Profile/EditProfile.jsx
  src/pages/Profile/MyPage.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/pages/QuestionPage/QuestionPost.jsx
  src/pages/index.js
  src/router.jsx
  src/stores/usePostStore.js
  src/utils/convertHTMLToText.js
  src/utils/getDetailedAddress.js
Labels: 🔨Feature

#141 회원가입에서 카테고리 받기
  package-lock.json
  package.json
  src/components/CategoryButton.jsx
  src/pages/SelectCategory.jsx
  src/pages/SignUp.jsx
Labels: 🔨Feature

#145 [Feat] 질문 게시글 수정 페이지 구현
  src/components/Board/PostImgButton.jsx
  src/components/Board/PostUser.jsx
  src/components/Board/QuestionForm.jsx
  src/components/Board/SelectCategory.jsx
  src/components/Map/StudyMap.jsx
  src/components/Map/TrackLocation.jsx
  src/components/MoreModal.jsx
  src/components/TopNav.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/pages/QuestionPage/QuestionEdit.jsx
  src/pages/index.js
  src/router.jsx
  src/stores/useAuthorStore.js
Labels: ⚠️Bug, 🔨Feature

#148 [Style] 모바일 사이즈 변경
  src/App.jsx
  src/api/getPbImageURL.js
  src/components/AddressSearch.jsx
  src/components/BannerSwiper.jsx
  src/components/Board/Reply.jsx
  src/components/CategoryButton.jsx
  src/components/Chat/ChatModal.jsx
  src/components/Chat/ChatNotice.module.css
  src/components/CheckButton.jsx
  src/components/DateButton.jsx
  src/components/FooterNav.jsx
  src/components/InputText.jsx
  src/components/Map/StudyMap.jsx
  src/components/MyPage/EditButton.jsx
  src/components/MyPage/EditInput.jsx
  src/components/MyPage/MyProfile.jsx
  src/components/MyPage/ProfileButton.jsx
  src/components/MyPage/ProfileCard.jsx
  src/components/MyPage/ProfileEditSection.jsx
  src/components/MyPage/ProfileImg.jsx
  src/components/MyPage/ProfileInfo.jsx
  src/components/NormalButton.jsx
  src/components/SearchBar.jsx
  src/components/SendMessageBar.jsx
  src/pages/Chat/Chatroom.jsx
  src/pages/LandingPage.jsx
  src/pages/Login.jsx
  src/pages/Profile/EditProfile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/pages/SelectCategory.jsx
  src/pages/SignUp.jsx
  src/utils/downloadImage.js
Labels: ⚠️Bug, 💄Styling, 🔨Feature

#154 [Feat] 스터디 게시글 구단위 렌더링 구현
  src/components/Board/QuestionForm.jsx
  src/components/Chat/ChatBoard.jsx
  src/components/Map/StudyMap.jsx
  src/components/MyPage/UserProfileInfo.jsx
  src/components/QuestionList.jsx
  src/components/SearchBar.jsx
  src/pages/Chat/Chatroom.jsx
  src/pages/HomePage.jsx
  src/pages/Login.jsx
  src/pages/Profile/UserProfile.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/pages/QuestionPage/QuestionPage.jsx
  src/pages/SelectCategory.jsx
  src/utils/extractCityDistrict.js
  src/utils/index.js
Labels: ⚠️Bug, 💄Styling, 🔨Feature

#153 [Feat] 검색페이지 기능 구현
  package-lock.json
  src/components/SearchBar.jsx
  src/components/SearchIcon.jsx
  src/pages/Search.jsx
  src/pages/SignUp.jsx
Labels: 🔨Feature

#157 [BugFix] 오류 수정
  public/_redirects
  src/components/Board/PostUser.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/HomePage.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/stores/useChatListStore.js
  src/utils/extractCityDistrict.js
Labels: ⚠️Bug

#160 [BugFix] 오류 수정
  src/components/Chat/ChatBoard.jsx
  src/pages/Chat/Chatroom.jsx
  src/stores/useChatListStore.js
Labels: 🔨Feature

#163 [BugFix] 오류 수정
  src/api/getPbImageURL.js
  src/components/Chat/ChatBoard.jsx
Labels: ⚠️Bug

#175 [Feat] 채팅창 모달 수정, 채팅 모달 애니메이션 추가
  src/components/Chat/ChatBoard.jsx
  src/components/Chat/ChatModal.jsx
  src/components/SendMessageBar.jsx
  src/pages/Chat/Chatroom.jsx
Labels: ⚠️Bug, 🔨Feature

#179 [Bugfix] 댓글 오류 수정
  src/components/Board/PostImgButton.jsx
  src/components/Board/QuestionForm.jsx
  src/components/Board/Reply.jsx
  src/components/Chat/ChatModal.jsx
  src/components/PostDetail.jsx
  src/pages/Chat/Chatroom.jsx
  src/pages/HomePage.jsx
  src/pages/Map.jsx
  src/pages/Profile/EditProfile.jsx
  src/pages/Profile/ProfileDetail.jsx
  src/pages/QuestionPage/QuestionDetailPage.jsx
  src/pages/QuestionPage/QuestionPage.jsx
  src/pages/Search.jsx
  src/pages/StudyDetail.jsx
  src/stores/usePostStore.js
Labels: ⚠️Bug, 💄Styling

#181 [BugFix] 카테고리 fetch 요청 에러 수정
  src/pages/QuestionPage/QuestionPage.jsx
Labels: ⚠️Bug
